<?php

/**
 * Created by PhpStorm.
 * User: xuguozhi
 * Date: 2017/1/19
 * Time: 10:48
 */

namespace app\modules\v1;

use Yii;
use yii\base\Component;

class Module extends \yii\base\Module
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        // 从config.php加载配置来初始化模块
        $config = require(__DIR__ . '/config/config.php');
        $components = $config['components'];
        // 重新配置相关组件
        Yii::$app->setComponents($components);
    }
}