<?php

/**
 * Created by PhpStorm.
 * User: xuguozhi
 * Date: 2017/1/19
 * Time: 10:48
 */

namespace app\modules\v1;

use Yii;

class Module extends \yii\base\Module
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}